languages:
- German
- English
opts:
  detectImageOrientation:
exports:
- outputFileFormat: PDFA
  pdfaPictureResolution: original
  pdfaQuality: 85
  pdfaExportMode: ImageOnText
  outputFileName: '%INPUT%.pdf'
- outputFileFormat: PDFA
  pdfaPictureResolution: original
  pdfaQuality: 85
  pdfaExportMode: TextOnly
  outputFileName: '%INPUT%_text.pdf'
- outputFileFormat: Text 
  txtInsertEmptyLineBetweenParagraphs:
  txtEncodingType: UTF8
  outputFileName: '%INPUT%.txt'
- outputFileFormat: XML 
  outputFileName: '%INPUT%.xml'
