languages:
- German
- English
opts:
  detectImageOrientation:
exports:
- outputFileFormat: PDFA
  pdfaPictureResolution: original
  pdfaQuality: 85
  pdfaExportMode: ImageOnText
  outputFileName: '{NAME}.pdf'
- outputFileFormat: PDFA
  pdfaPictureResolution: original
  pdfaQuality: 85
  pdfaExportMode: TextOnly
  outputFileName: '{NAME}_text.pdf'
- outputFileFormat: Text 
  txtInsertEmptyLineBetweenParagraphs:
  txtEncodingType: UTF8
  outputFileName: '{NAME}.txt'
- outputFileFormat: XML 
  outputFileName: '{NAME}.xml'
